[main]
font=JetBrains Mono:size=10
line-height=20
dpi-aware=yes
lines=10
width=40

[colors]
# Nord 0
background=2E3440FF
# Nord 4
text=D8DEE9FF
# Nord 8
match=88C0D0FF
# Nord 2
selection=434C5EFF
# Nord 6
selection-text=ECEFF4FF
# Nord 3
border=4C566AFF
