[main]
# Font and size
font=JetBrainsMono:size=23
# Prevent foot from mis-scaling under Hyprland
dpi-aware=no

# Use a reasonable initial terminal size
term=xterm-256color
initial-window-size-chars=80x24
pad=4x4

[scrollback]
# Allow scrolling with Shift+PageUp/PageDown
lines=10000

[colors]
# Standard dark theme
# foreground=ebdbb2
# background=282828

alpha=0.9
# alpha-mode=default # Can be `default`, `matching` or `all`

foreground=ECEFF4
background=2E3440

regular0=3B4252  # black
regular1=BF616A  # red
regular2=A3BE8C  # green
regular3=EBCB8B  # yellow
regular4=81A1C1  # blue
regular5=B48EAD  # magenta
regular6=88C0D0  # cyan
regular7=E5E9F0  # white

bright0=4C566A   # bright black
bright1=BF616A   # bright red
bright2=A3BE8C   # bright green
bright3=EBCB8B   # bright yellow
bright4=81A1C1   # bright blue
bright5=B48EAD   # bright magenta
bright6=8FBCBB   # bright cyan
bright7=ECEFF4   # bright white
