preload = /home/JanCoe/OneDrive/Pictures/Wallpaper/PostApocalypticBike.png
# preload = /home/JanCoe/OneDrive/Pictures/Wallpaper/33214.jpg
# preload = /home/JanCoe/OneDrive/Pictures/Wallpaper/dark-anime.jpg
# preload = /home/JanCoe/OneDrive/Pictures/Wallpaper/fate.jpg
# preload = /home/JanCoe/OneDrive/Pictures/Wallpaper/touhou_anime.jpg

wallpaper = HDMI-A-1,/home/JanCoe/OneDrive/Pictures/Wallpaper/PostApocalypticBike.png

splash = true
