# preload = /home/JanCoe/OneDrive/Pictures/Wallpaper/PostApocalypticBike.png
# preload = /home/JanCoe/OneDrive/Pictures/Wallpaper/33214.jpg
# preload = /home/JanCoe/OneDrive/Pictures/Wallpaper/dark-anime.jpg
preload = /home/JanCoe/OneDrive/Pictures/Wallpaper/fate.jpg
# preload = /home/JanCoe/OneDrive/Pictures/Wallpaper/touhou_anime.jpg

# Need a line like this for every monitor. Find monitor names with 'hyprctl monitors'
wallpaper = DP-1,/home/JanCoe/OneDrive/Pictures/Wallpaper/fate.jpg

splash = false 
