# Add CTRL to a keycombination to move the active thing there

$mainMod = SUPER
$lft = H
$dwn = J
$up_ = K
$rgt = L
$this_dir = $HOME/.config/hypr

# See https://wiki.hyprland.org/Configuring/Binds/ for more
# System and window management
bind = $mainMod, F, fullscreen,
bind = $mainMod, Q, killactive,
bind = $mainMod, EQUAL, layoutmsg, orientationright
bind = $mainMod, MINUS, layoutmsg, orientationleft

# bind = $mainMod, SPACE, togglesplit,
bind = $mainMod SHIFT, SPACE, togglefloating,
bind = $mainMod SHIFT, P, pseudo,
bind = $mainMod SHIFT, S, togglespecialworkspace, magic
bind = $mainMod SHIFT, R, exec, hyprctl reload

# Applications and utilities
bind = $mainMod, M, exec, system-menu
bind = $mainMod, D, exec, run-or-kill $menu 
bind = $mainMod, E, exec, run-or-kill $files
bind = $mainMod, P, exec, run-or-kill pavucontrol --tab=3
bind = $mainMod, N, exec, $termapp -e nvim
bind = $mainMod, RETURN, exec, $terminal
bind = $mainMod, B, exec, $this_dir/focus-or-launch "Vivaldi - Vivaldi" $browser
bind = $mainMod, A, exec, focus-or-launch claude.ai_/ "$webapp=https://claude.ai"
bind = $mainMod, C, exec, focus-or-launch chatgpt.com_/ "$webapp=https://chatgpt.com"
bind = $mainMod, Y, exec, focus-or-launch youtube.com_/ "$webapp=https://youtube.com"
bind = $mainMod, X, exec, focus-or-launch excalidraw.com_/ "$webapp=https://excalidraw.com"
bind = $mainMod, W, exec, focus-or-launch web.whatsapp.com_/ "$webapp=https://web.whatsapp.com"
bind = $mainMod, O, exec, focus-or-launch obsidian "md.obsidian.Obsidian -disable-gpu"
bind = $mainMod, slash, exec, focus-or-launch "1Password" 1password

# Focus movement 
bind = $mainMod, $lft, movefocus, l
bind = $mainMod, $dwn, movefocus, d
bind = $mainMod, $up_, movefocus, u
bind = $mainMod, $rgt, movefocus, r

# Window movement 
bind = $mainMod CTRL, $lft, movewindow, l
bind = $mainMod CTRL, $dwn, movewindow, d
bind = $mainMod CTRL, $up_, movewindow, u
bind = $mainMod CTRL, $rgt, movewindow, r
bind = $mainMod CTRL, S, movetoworkspace, special:magic

# Switch workspaces
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# Move active window to a workspace
bind = $mainMod CTRL, 1, movetoworkspacesilent, 1
bind = $mainMod CTRL, 2, movetoworkspacesilent, 2
bind = $mainMod CTRL, 3, movetoworkspacesilent, 3
bind = $mainMod CTRL, 4, movetoworkspacesilent, 4
bind = $mainMod CTRL, 5, movetoworkspacesilent, 5
bind = $mainMod CTRL, 6, movetoworkspacesilent, 6
bind = $mainMod CTRL, 7, movetoworkspacesilent, 7
bind = $mainMod CTRL, 8, movetoworkspacesilent, 8
bind = $mainMod CTRL, 9, movetoworkspacesilent, 9
bind = $mainMod CTRL, 0, movetoworkspacesilent, 10

# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# Laptop multimedia keys for volume and LCD brightness
bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindel = ,XF86MonBrightnessUp, exec, brightnessctl -e4 -n2 set 5%+
bindel = ,XF86MonBrightnessDown, exec, brightnessctl -e4 -n2 set 5%-

# Requires playerctl
bindl = , XF86AudioNext, exec, playerctl next
bindl = , XF86AudioPause, exec, playerctl play-pause
bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF86AudioPrev, exec, playerctl previous
