#!/usr/bin/env bash

identifier="${1}"  # The application’s identifier (from `hyprctl clients`)
launch_cmd="${2}"  # Command to launch the application

addr=$(hyprctl clients -j | jq -r --arg id "$identifier" \
  '.[] | select(.initialTitle == $id) | .address' | head -n 1)

[[ -z "$addr" ]] && addr=$(hyprctl clients -j | jq -r --arg id "$identifier" \
  '.[] | select(.initialClass == $id) | .address' | head -n 1)

if [[ -n "$addr" ]]; then
    hyprctl dispatch focuswindow address:"$addr"
else
    $launch_cmd &
fi
