#!/usr/bin/env bash
set -euo pipefail

# This script installs the kew music player (assuming all its dependencies are already installed).

mkdir -p "$HOME"/Apps/kew
git clone https://github.com/ravachol/kew.git "$HOME"/Apps/kew
cd "$HOME"/Apps/kew || exit
make -j4
sudo make install
make clean
kew path "$HOME"/Media/Music/Vault  # Replace with the path of your music.
