#!/usr/bin/env bash
set -euo pipefail

PKG_COPR=(
  lihaohong/yazi
  rubemlrm/nordzy-icon # for nordic theme
  wezfurlong/wezterm-nightly
  solopasha/hyprland
)
PKG_DNF=(
    @development-tools
    cmake
    fuse-libs  # needed to run AppImages (Jetbrains toolbox is an AppImage)
    openssl-devel  # needed for cargo-update
    libxcrypt-compat  # needed for Synology HyperBackupExplorer, not done yet
    # fonts and themes
    ibm-plex-sans-fonts
    ibm-plex-serif-fonts 
    jetbrains-mono-fonts
    nordzy-icon
    papirus-icon-theme
    gtk2
    gtk-murrine-engine  # for GTK themes to render correctly
    lxappearance  # to set GTK appearance 
    rsms-inter-fonts
    # hyprland
    hyprland
    hyprland-qtutils
    # rest 
    flatpak
    # CLI utils 
    bat
    dnf-utils 
    fastfetch
    fd
    fzf
    gh
    git-lfs
    htop
    ripgrep 
    ShellCheck
    stow
    tldr
    tmux
    trash
    uutils-coreutils
    wofi
    yazi 
    zoxide
    zsh
    # development utils
    ruff
    toolbox
    uv
    # applications 
    @vlc  # install extra plugins too
    asciidoctor
    cheese
    neomutt
    neovim
    nushell  # need to have added the repo
    onedrive
    thunderbird
    vivaldi-stable  # need to have added the repo
    wezterm  # need to have added the repo
)
PKG_CARGO=(
    cargo-update
    du-dust
    dua 
    hyperfine
    starship
    tokei
)
FLATPAKS=(
    ch.protonmail.protonmail-bridge
    md.obsidian.Obsidian
    com.github.tchx84.Flatseal
    us.zoom.Zoom
)

read -s -r -p "Enter your sudo password: " pwd
echo

echo "==> Refreshing Fedora..."
echo "$pwd" | sudo -S dnf upgrade --refresh -y

echo "==> Adding nushell to repo and installing..."
install-nushell

echo "==> Adding Vivaldi to repo and installing..."
install-vivaldi

echo "==> Enabling COPR packages..."
echo "$pwd" | sudo -S dnf copr enable "${PKG_COPR[@]}"

echo "==> Installing DNF packages..."
echo "$pwd" | sudo -S dnf install -y "${PKG_DNF[@]}"

echo "==> Installing Rust..."
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
[[ -f "$HOME"/.cargo/env ]] && source "$HOME"/.cargo/env

echo "==> Installing cargo packages..."
cargo install "${PKG_CARGO[@]}"

echo "==> Add flathub to repo..."
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

echo "==> Installing Flathub packages..."
flatpak install flathub "${FLATPAKS[@]}"

# i3 only
# echo "==> Setting background..."
# feh --bg-scale ~/.dotfiles/backgrounds/touhou_anime.jpg
