#!/usr/bin/env bash
set -euo pipefail

# Install packages on a new Mac

echo "===> Installing pre-requisites for Git and Homebrew"
xcode-select --install

echo "===> Installing Homebrew..."
env bash -c "$(curl fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

echo "===> Installing brews..."
brew bundle --file ~/.dotfiles/notes/Brewfile

echo "===> Authorising github..."
gh auth login

echo "===> Cloning dotfiles repository..."
gh repo clone JanCoe/dotfiles ~/.dotfiles

echo "===> Installing rust..."
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
. "$HOME/.cargo/env"

echo "===> Installing cargo packages..." 
PKG_CARGO=(
    cargo-update
    du-dust
    dua
    hyperfine
    nu
    nu_plugin_formats
    nu_plugin_gstat
    nu_plugin_inc
    nu_plugin_polars
    nu_plugin_query
    ruff 
    starship
    tokei
    zoxide
)
cargo install "${PKG_CARGO[@]}"
