#!/usr/bin/env bash
set -euo pipefail

PKG_COPR=(
  lihaohong/yazi
  rubemlrm/nordzy-icon # for nordic theme
  wezfurlong/wezterm-nightly 
)
PKG_DNF=(
    @development-tools
    cmake
    fuse-libs  # needed to run AppImages (Jetbrains toolbox is an AppImage)
    openssl-devel  # needed for cargo-update
    # libxcrypt-compat  # needed for Synology HyperBackupExplorer, not done yet
    # fonts and themes
    ibm-plex-sans-fonts
    ibm-plex-serif-fonts 
    jetbrains-mono-fonts
    nordzy-icon
    papirus-icon-theme
    rsms-inter-fonts
    # i3 only 
    picom
    # rest 
    flatpak
    multimedia
    # CLI utils 
    bat
    dnf-utils 
    fastfetch
    fd
    fzf
    gh
    git-lfs
    htop
    ripgrep 
    ShellCheck
    stow
    tldr
    tmux
    trash
    uutils-coreutils
    yazi 
    zoxide
    zsh
    # development utils
    ruff
    toolbox
    uv
    # applications 
    @vlc  # install extra plugins too
    asciidoctor
    cheese
    neomutt
    neovim
    nushell
    onedrive
    thunderbird
    wezterm
)
PKG_CARGO=(
    cargo-update
    du-dust
    dua 
    hyperfine
    starship
    tokei
)
FLATPAKS=(
    ch.protonmail.protonmail-bridge
    com.vivaldi.Vivaldi
    md.obsidian.Obsidian
    us.zoom.Zoom
)

read -s -p -r "Enter your sudo password: " pwd
echo

echo "==> Refreshing Fedora..."
echo "$pwd" | sudo -S dnf upgrade --refresh -y

# Do this step manually.
echo "==> Adding nushell to repo..."
config_text="[gemfury-nushell]
name=Gemfury Nushell Repo
baseurl=https://yum.fury.io/nushell/
enabled=1
gpgcheck=0
gpgkey=https://yum.fury.io/nushell/gpg.key"
echo "$config_text" | sudo tee /etc/yum.repos.d/fury-nushell.repo

echo "==> Enabling COPR packages..."
echo "$pwd" | sudo -S dnf copr enable "${PKG_COPR[@]}"

echo "==> Installing DNF packages..."
echo "$pwd" | sudo -S dnf install -y "${PKG_DNF[@]}"

echo "==> Installing Rust..."
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
[[ -f "$HOME"/.cargo/env ]] && source "$HOME"/.cargo/env

echo "==> Installing cargo packages..."
cargo install "${PKG_CARGO[@]}"

echo "==> Add flathub to repo..."
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

echo "==> Installing Flathub packages..."
flatpak install flathub "${FLATPAKS[@]}"

# i3 only
echo "==> Installing lockscreen..." 
cd ~/Downloads
git clone https://github.com/meskarune/i3lock-fancy.git
cd i3lock-fancy
sudo make install

# i3 only
echo "==> Setting background..."
feh --bg-scale ~/.dotfiles/backgrounds/touhou_anime.jpg
