#!/usr/bin/env bash
set -euo pipefail
commands=("bash" "hyprland" "hyprland-keymaps" "nvim" "nvim-keymaps" "profile" "wezterm")
menu=$(printf "%s\n" "${commands[@]}")
selected=$(echo "$menu" | wofi --dmenu --width 250 --lines 10 --prompt "Configs")
if [[ -n "$selected" ]]; then
    case $selected in
        bash)
            nvim "$HOME/.bashrc" ;;
        hyprland)
            nvim "$XDG_CONFIG_HOME/hypr/hyprland.conf" ;;
        "hyprland-keymaps")
            nvim "$XDG_CONFIG_HOME/hypr/bindings.conf" ;;
        nvim)
            nvim "$XDG_CONFIG_HOME/nvim/init.lua" ;;
        "nvim-keymaps")
            nvim "$XDG_CONFIG_HOME/nvim/lua/config/keymaps.lua" ;;
        profile)
            nvim "$HOME/.profile" ;;
        waybar)
            nvim "$XDG_CONFIG_HOME/waybar/config.jsonc" ;;
        wezterm)
            nvim "$XDG_CONFIG_HOME/wezterm/wezterm.lua" ;;
        *) ;;
    esac
fi
