#!/usr/bin/env bash
set -euo pipefail
commands=("Configs" "System")
menu=$(printf "%s\n" "${commands[@]}")
selected=$(echo "$menu" | wofi --dmenu --width 250 --lines 5 --prompt "Select")
if [[ -n "$selected" ]]; then
    case $selected in
        Configs)
            "$HOME/.dotfiles/scripts/menu-configs" ;;
        System)
            "$HOME/.dotfiles/scripts/menu-system" ;;
        *) ;;
    esac
fi
