#!/bin/bash

read -s -p "Enter Nas password: " pwd
echo
echo

read -p "Read-only (r) or read-write (w)?: " mode

# This assumes that NAS IP has been mapped to 'nas' in /etc/hosts
if [[ $mode == "r" ]] then
    sudo mount -t cifs //nas/music ~/Music/Nas -o username=highgate,password=$pwd,vers=3.0
elif [[ $mode == "w" ]] then
    sudo mount -t cifs //nas/music ~/Music/Nas -o username=highgate,password=$pwd,vers=3.0,uid=$(id -u),gid=$(id -g),rw
else
    echo "Option not recognised."
fi
