#!/usr/bin/env bash

read -s -p "Enter Nas password: " pwd
echo
echo

if [[ -z "$1" ]]; then
    echo "Defaulting to read-only. Pass argument of 'w' for write mode." 
fi
mode="${1:-r}"

# This assumes that NAS IP has been mapped to 'nas' in /etc/hosts
if [[ $mode == "r" ]] then
    sudo mount -t cifs //nas/movie ~/Media/Movie -o username=highgate,password=$pwd,vers=3.0
elif [[ $mode == "w" ]] then
    sudo mount -t cifs //nas/movie ~/Media/Movie -o username=highgate,password=$pwd,vers=3.0,uid=$(id -u),gid=$(id -g),rw
else
    echo "Option not recognised."
fi
