#!/usr/bin/env bash

# Takes an argument of the application to run.
# If it is running already, kill it.
# Otherwise launch it with any optional arguments.

# shellcheck disable=SC2015
pgrep "$1" &> /dev/null && killall "$1" || "$@"
