#!/usr/bin/env bash
set -euo pipefail

call_wofi() {
    wofi --dmenu --width 600 --lines 20 --location=top_left
}

menu() (
    local menu_items=("$@")
    local menu_display
    menu_display=$(printf "%s\n" "${menu_items[@]}" | awk -F: '{print $2 " " $1}')
    
    local selected
    selected=$(echo "$menu_display" | call_wofi)

    local label="${selected#* }"

    for item in "${menu_items[@]}"; do
        IFS=":" read -r item_label _ item_cmd <<< "$item"
        if [[ "$item_label" == "$label" ]]; then
            # If the command starts with "menu ", treat the rest as an array name
            if [[ $item_cmd == menu\ * ]]; then
                local array_name="${item_cmd#menu }"
                local -n arr_ref="$array_name"  # nameref to the original array
                menu "${arr_ref[@]}"
            else
                read -r -a cmd <<< "$item_cmd"  # split into array
                "${cmd[@]}"
                exit 0
            fi
        fi
    done
)

pdf() (
    list=$(find ~/OneDrive/Books -type f -name "*.pdf"  2>/dev/null -printf "%f::%p\n")
    choice=$(echo "$list" | cut -d: -f1 | call_wofi)
    file=$(echo "$list" | grep -F "$choice::" | head -n1 | cut -d: -f3-) 
    [ -n "$file" ] && zathura "$file" &
)

start_nvim="$TERMINAL start -- nvim"

configs=(
    "...back:⬅️:menu main"
    "...edit:📝:$start_nvim $0"
    "aliases::$start_nvim $HOME/.aliases"
    "bash::$start_nvim $HOME/.bashrc"
    "foot::$start_nvim $XDG_CONFIG_HOME/foot/foot.ini"
    "hyprland-bindings::$start_nvim $XDG_CONFIG_HOME/hypr/bindings.conf"
    "hyprland::$start_nvim $XDG_CONFIG_HOME/hypr/hyprland.conf"
    "nvim-keymaps::$start_nvim $XDG_CONFIG_HOME/nvim/lua/config/keymaps.lua"
    "nvim::$start_nvim $XDG_CONFIG_HOME/nvim/init.lua"
    "profile::$start_nvim $HOME/.profile"
    "starship::$start_nvim $XDG_CONFIG_HOME/starship/starship.toml"
    "waybar-config::$start_nvim $XDG_CONFIG_HOME/waybar/config.jsonc"
    "waybar-style::$start_nvim $XDG_CONFIG_HOME/waybar/style.css"
    "wezterm::$start_nvim $XDG_CONFIG_HOME/wezterm/wezterm.lua"
)

connect=(
    "...back:⬅️:menu main"
    "...edit:📝:$start_nvim $0"
    "audio:🔊:pavucontrol"
    "bluetooth:🅱️:blueman-manager"
    "wifi:📶:nm-connection-editor"
)

system=(
    "...back:⬅️:menu main"
    "...edit:📝:$start_nvim $0"
    "monitor::toggle-monitor"
    "poweroff:⏹:poweroff"
    "reboot:🔄:reboot"
)

utilities=(
    "...back:⬅️:menu main"
    "...edit:📝:$start_nvim $0"
    "screenshot::screenshot"
)

media=(
    "...back:⬅️:menu main"
    "...edit:📝:$start_nvim $0"
    "pdf::pdf"
)

main=(
    "...edit:📝:$start_nvim $0"
    "configs:⚙️:menu configs"
    "connect:🔗:menu connect"
    "system:⚡:menu system"
    "utilities:🔧:menu utilities"
    "media::menu media"
)

menu "${main[@]}"
