#!/usr/bin/env bash
set -euo pipefail

START_TIME=$SECONDS

ASK_SUDO=true  # Set to false to skip password prompt when running as root

# Detect if running as root 
if [[ "$EUID" -eq 0 ]]; then
    ASK_SUDO=false
    set -x # to echo everything into logs when run with systemd
fi

if $ASK_SUDO; then
    sudo -v
fi

printf "%s\n" "==> Updating DNF packages..."
sudo dnf upgrade --refresh -y

printf "\n%s\n" "==> Cleaning up DNF..."
sudo dnf autoremove -y
sudo dnf clean all

if command -v flatpak &>/dev/null; then
    printf "\n%s\n" "==> Updating Flatpak apps..."
    flatpak update -y

    printf "\n%s\n" "==> Cleaning up unused Flatpak runtimes..."
    flatpak uninstall --unused -y
fi

if command -v cargo &>/dev/null; then
    printf "\n%s\n" "==> Updating Cargo packages..."
    cargo install-update --all
    printf "\n"
fi

printf "%s\n" "==> All updates and cleanup complete!"

printf "\n%s\n" "==> Checking if reboot is required..."
needs-restarting -r

set +x

ELAPSED=$(( SECONDS - START_TIME ))
printf "\n==> Total time: %d min %d sec\n" $(( ELAPSED / 60 )) $(( ELAPSED % 60 ))
